FORMAT: 1A
HOST: https://laravel.io/api

# Laravel.io API

This document describes the api for the Laravel.io portal.

## Threads [/threads]

### Retrieve some threads [GET]

+ Response 200 (application/json)

            [
                {
                    "subject": "Test Thread",
                    "body": "Test foo"
                }
            ]
