## Users [/users]

### Retrieve a list of users [GET]

+ Response 200 (application/json)

        [
            {
                "id": 1,
                "name": "Dries Vints",
                "username": "driesvints"
            }
        ]
